cgi.escape has been deprecated since version 3.2 and gone in 3.8.
Addressing Python 3.8 failure
AttributeError: module 'cgi' has no attribute 'escape'
      args = ("module 'cgi' has no attribute 'escape'",)
      with_traceback = <built-in method with_traceback of AttributeError object>