Update possible numerical uids/gids mismatch of SSSD directories in case /data was populated by a container from a different image.
Addressing
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //h1/a; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
or
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=https%3A//www.example.test/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20www.example.test.

caused by
[sssd] [confdb_write_ini] (0x0010): Can't delete old '/var/lib/sss/db/config.ldb'
[sssd] [main] (0x0010): Failed to write config DB: 'Permission denied'