The openssl no longer seems to be installed via other dependencies.
Addressing
Traceback (most recent call last):
  File "/usr/sbin/ipsilon-server-install", line 522, in <module>
    install(fplugins, opts)
  File "/usr/sbin/ipsilon-server-install", line 222, in install
    if plugin.configure(args, plugin_changes) == False:
  File "/usr/lib/python2.7/site-packages/ipsilon/providers/saml2idp.py", line 521, in configure
    cert.generate('idp', opts['hostname'])
  File "/usr/lib/python2.7/site-packages/ipsilon/tools/certs.py", line 27, in generate
    proc = Popen(command)
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Traceback (most recent call last):
  File "/usr/bin/ipsilon-client-install", line 589, in <module>
    saml2()
  File "/usr/bin/ipsilon-client-install", line 101, in saml2
    c.generate('certificate', args['hostname'])
  File "/usr/lib/python2.7/site-packages/ipsilon/tools/certs.py", line 27, in generate
    proc = Popen(command)
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory