Make sure www.example.test is checked.
Avoid working with pages which are still on the IdP server:
Not logged in
https://idp.example.test/idp/login/form?ipsilon_transaction_id=bc8def65-b161-4a02-b4ee-197e353e39c4
https://idp.example.test/idp/saml2/SSO/Continue?ipsilon_transaction_id=bc8def65-b161-4a02-b4ee-197e353e39c4
Traceback (most recent call last):
  File "/usr/local/bin/test-saml.py", line 34, in <module>
    title = driver.find_element_by_xpath("//h1/a")
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 855, in find_element
    'value': value})['value']
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //h1/a

make: *** [Makefile:14: test] Error 1